import type { Metadata } from "next";
import "./globals.css";
// import { Outfit } from "next/font/google";
import { Josefin_Sans } from "next/font/google";
import LayoutWrapper from "./components/LayoutWrapper";
import Header from "./components/Header";
import Footer from "./components/Footer";


const JosefinSansFont = Josefin_Sans({
  display: "swap",
  subsets: ["latin"],
  weight: ["400", "500", "700"], // Add the weights you need
});

// const OutfitFont = Outfit({
//   display: "swap",
//   subsets: ["latin"],
//   weight: ["500"],
// })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${JosefinSansFont.className}`}
      >
        <LayoutWrapper>
          <Header />
          {children}
          <Footer  />
        </LayoutWrapper>
      </body>
    </html>
  );
}
